// Kanonische Reihenfolge der Bibelbücher (evangelisch) mit Kurzform und Testament.
// - name: so, wie das Buch in der Bibelstelle einer Andacht geschrieben wird
//         (Frontmatter-Feld "stelle", z. B. "Johannes 1,11" → name "Johannes").
// - kurz: kurze Anzeige auf den Buch-Kacheln (wie in der Übersicht).
// - testament: "at" (Altes Testament) oder "nt" (Neues Testament).
//
// Wird sowohl in eleventy.config.js (Gruppierung der Andachten nach Buch/Kapitel)
// als auch in den Vorlagen verwendet.
module.exports = [
  // --- Altes Testament ---
  { name: "1. Mose", kurz: "1. Mo", testament: "at" },
  { name: "2. Mose", kurz: "2. Mo", testament: "at" },
  { name: "3. Mose", kurz: "3. Mo", testament: "at" },
  { name: "4. Mose", kurz: "4. Mo", testament: "at" },
  { name: "5. Mose", kurz: "5. Mo", testament: "at" },
  { name: "Josua", kurz: "Jos", testament: "at" },
  { name: "Richter", kurz: "Ri", testament: "at" },
  { name: "Rut", kurz: "Rt", testament: "at" },
  { name: "1. Samuel", kurz: "1. Sam", testament: "at" },
  { name: "2. Samuel", kurz: "2. Sam", testament: "at" },
  { name: "1. Könige", kurz: "1. Kön", testament: "at" },
  { name: "2. Könige", kurz: "2. Kön", testament: "at" },
  { name: "1. Chronik", kurz: "1. Chr", testament: "at" },
  { name: "2. Chronik", kurz: "2. Chr", testament: "at" },
  { name: "Esra", kurz: "Esra", testament: "at" },
  { name: "Nehemia", kurz: "Neh", testament: "at" },
  { name: "Ester", kurz: "Est", testament: "at" },
  { name: "Hiob", kurz: "Hiob", testament: "at" },
  { name: "Psalm", kurz: "Ps", testament: "at" },
  { name: "Sprüche", kurz: "Spr", testament: "at" },
  { name: "Prediger", kurz: "Pred", testament: "at" },
  { name: "Hoheslied", kurz: "Hld", testament: "at" },
  { name: "Jesaja", kurz: "Jes", testament: "at" },
  { name: "Jeremia", kurz: "Jer", testament: "at" },
  { name: "Klagelieder", kurz: "Klgl", testament: "at" },
  { name: "Hesekiel", kurz: "Hes", testament: "at" },
  { name: "Daniel", kurz: "Dan", testament: "at" },
  { name: "Hosea", kurz: "Hos", testament: "at" },
  { name: "Joel", kurz: "Joel", testament: "at" },
  { name: "Amos", kurz: "Amos", testament: "at" },
  { name: "Obadja", kurz: "Obad", testament: "at" },
  { name: "Jona", kurz: "Jona", testament: "at" },
  { name: "Micha", kurz: "Mich", testament: "at" },
  { name: "Nahum", kurz: "Nah", testament: "at" },
  { name: "Habakuk", kurz: "Hab", testament: "at" },
  { name: "Zefanja", kurz: "Zeph", testament: "at" },
  { name: "Haggai", kurz: "Hag", testament: "at" },
  { name: "Sacharja", kurz: "Sach", testament: "at" },
  { name: "Maleachi", kurz: "Mal", testament: "at" },
  // --- Neues Testament ---
  { name: "Matthäus", kurz: "Mt", testament: "nt" },
  { name: "Markus", kurz: "Mk", testament: "nt" },
  { name: "Lukas", kurz: "Lk", testament: "nt" },
  { name: "Johannes", kurz: "Joh", testament: "nt" },
  { name: "Apostelgeschichte", kurz: "Apg", testament: "nt" },
  { name: "Römer", kurz: "Röm", testament: "nt" },
  { name: "1. Korinther", kurz: "1. Kor", testament: "nt" },
  { name: "2. Korinther", kurz: "2. Kor", testament: "nt" },
  { name: "Galater", kurz: "Gal", testament: "nt" },
  { name: "Epheser", kurz: "Eph", testament: "nt" },
  { name: "Philipper", kurz: "Phil", testament: "nt" },
  { name: "Kolosser", kurz: "Kol", testament: "nt" },
  { name: "1. Thessalonicher", kurz: "1. Thes", testament: "nt" },
  { name: "2. Thessalonicher", kurz: "2. Thes", testament: "nt" },
  { name: "1. Timotheus", kurz: "1. Tim", testament: "nt" },
  { name: "2. Timotheus", kurz: "2. Tim", testament: "nt" },
  { name: "Titus", kurz: "Tit", testament: "nt" },
  { name: "Philemon", kurz: "Phlm", testament: "nt" },
  { name: "Hebräer", kurz: "Heb", testament: "nt" },
  { name: "Jakobus", kurz: "Jak", testament: "nt" },
  { name: "1. Petrus", kurz: "1. Pet", testament: "nt" },
  { name: "2. Petrus", kurz: "2. Pet", testament: "nt" },
  { name: "1. Johannes", kurz: "1. Joh", testament: "nt" },
  { name: "2. Johannes", kurz: "2. Joh", testament: "nt" },
  { name: "3. Johannes", kurz: "3. Joh", testament: "nt" },
  { name: "Judas", kurz: "Jud", testament: "nt" },
  { name: "Offenbarung", kurz: "Off", testament: "nt" },
];
